<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-IT7JOLC2" failures="3" tests="21" name="com.myproject.tests.LoginPageUITest" time="194.947" errors="0" timestamp="2025-09-09T03:08:45 IST" skipped="0">
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyScrollUpAppearance" time="6.463"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyLoginButtonAvailable" time="6.020"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifySignupFields" time="5.192"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyHomeNavigationFromLogin" time="8.741"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifySignupLoginNavigatesAndLoginFormDisplayed" time="6.405"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyVideoTutorialsNavigationFromLogin" time="9.335"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyScrollUpAppears" time="7.289"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyScrollUpClickBehavior" time="5.954"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifySubscriptionDuplicateEmail" time="26.402">
    <failure message="Subscription should return visible response for duplicate email submission expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Subscription should return visible response for duplicate email submission expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.myproject.tests.LoginPageUITest.verifySubscriptionDuplicateEmail(LoginPageUITest.java:104)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifySubscriptionDuplicateEmail -->
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyTestCasesNavigationFromLogin" time="7.259"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifySubscriptionValidEmail" time="5.694"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyContactUsNavigationFromLogin" time="15.704">
    <failure message="Contact Us navigation should work from login page expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Contact Us navigation should work from login page expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.myproject.tests.LoginPageUITest.verifyContactUsNavigationFromLogin(LoginPageUITest.java:83)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyContactUsNavigationFromLogin -->
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyCartNavigationFromLogin" time="5.187"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifySignupButtonAvailable" time="5.793"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyApiTestingNavigationFromLogin" time="7.173"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyLoginSectionAccessible" time="5.513"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifySubscriptionInvalidEmail" time="25.241"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyLogoOnLoginPage" time="5.765"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyLoginFields" time="5.212"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyLayoutConforms" time="5.488"/>
  <testcase classname="com.myproject.tests.LoginPageUITest" name="verifyProductsNavigationFromLogin" time="19.117">
    <failure message="Products navigation should work from login page expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Products navigation should work from login page expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.myproject.tests.LoginPageUITest.verifyProductsNavigationFromLogin(LoginPageUITest.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyProductsNavigationFromLogin -->
</testsuite> <!-- com.myproject.tests.LoginPageUITest -->
